branch-defaults:
  deploy:
    environment: Docuserv
  master:
    environment: docuserv
    group_suffix: null
global:
  application_name: Docuserv
  default_ec2_keyname: aws-eb
  default_platform: Python 3.4
  default_region: us-east-1
  profile: eb-cli
  sc: git
